name: "Lint helm package"
description: "Lint helm chart"
inputs:
  chart-path:
    description: Path to the chart to publish
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: Lint helm chart
      run: helm lint ${{inputs.chart-path}}
      shell: bash